import React from 'react';
import {Button, Icon, Layout, message, Modal, Slider, Switch} from 'antd';

import HeaderComponent from "../header";
import SidebarComponent from "../sidebar";
import LiveFeedComponent from "../live-feed-component";

import './layout.css'
import Title from "antd/es/typography/Title";

const {Header, Content} = Layout;
const MyIcon = Icon.createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/font_1305999_xwbq1mtlygf.js', // generated by iconfont.cn
});

const employeeJson = {
    "num_employees": 925,
    "num_present": 801,
    "check_in": {
        "on_time": 369,
        "before_time": 207,
        "late": 225,
        "absent": 124
    },
    "times_in_office": {
        "format": ["inside_office", "outside_office"],
        "0700": [100, 100],
        "0800": [400, 200],
        "0900": [200, 250],
        "1000": [350, 300],
        "1100": [477, 223],
        "present_time": [477, 223]
    },
    "check_out": {
        "on_time": 334,
        "before_time": 135,
        "late": 332,
        "absent": 124
    }
};

export default class LayoutComponent extends React.Component {

    state = {
        showModal: false
    };

    showModal = () => {
        this.setState({
            showModal: true,
        });
    };

    handleOk = e => {
        console.log(e);
        this.setState({
            showModal: false,
        });
        message.success('Filter Applied Successfully.');
    };

    handleCancel = e => {
        console.log(e);
        this.setState({
            showModal: false,
        });
    };

    render() {
        return (
            <div style={{height: "100vh"}}>
                <Layout style={{height: "100vh"}}>
                    <HeaderComponent/>
                    <Layout style={{background: '#212121', overflowY: "hidden"}}>
                        <SidebarComponent/>
                        {/*<div>*/}
                        {/*<MyIcon type={"icon-radio-waves"} style={{color: "#F18585", fontSize: "24px"}}/>*/}
                        {/*<span style={{color: "#F18585", marginLeft: "10px"}}>Live Feed</span>*/}
                        {/*</div>*/}
                        <Layout style={{margin: '36px', marginTop: 0, background: '#303741', overflowY: "hidden"}}>
                            <Header style={{
                                background: "#212121",
                                display: "flex",
                                justifyContent: "space-between",
                                alignItems: "center"
                            }}>
                                <Title
                                    style={{color: "#F18585", fontSize: "20px"}}
                                    className={"blink"}
                                >
                                    <MyIcon type={"icon-radio-waves"}
                                            style={{color: "#F18585", fontSize: "24px", marginRight: "10px"}}/>
                                    Live Feed
                                </Title>
                                <Button ghost shape="round" icon="control" onClick={this.showModal}>
                                    Filter
                                </Button>
                            </Header>
                            <Content
                                style={{
                                    padding: 24,
                                    margin: 0,
                                    minHeight: 280,
                                    borderRadius: "5px",
                                    overflowY: "auto"
                                }}
                            >
                                <LiveFeedComponent chartData={employeeJson}/>
                            </Content>
                        </Layout>
                    </Layout>
                </Layout>
                <Modal
                    title="Basic Modal"
                    visible={this.state.showModal}
                    onOk={this.handleOk}
                    onCancel={this.handleCancel}
                    okText={"Apply"}
                >
                    <Slider defaultValue={30}/>
                    <Slider range defaultValue={[20, 50]}/>
                    View All: <Switch size="small" defaultChecked={false}/>
                </Modal>
            </div>
        )
    }
}