import React from 'react';
import {Badge, Menu} from "antd";
import {Icon, Layout} from "antd";

import "./sidebar.css"

const {Sider} = Layout;
const {SubMenu} = Menu;

const MyIcon = Icon.createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/font_1305999_xwbq1mtlygf.js', // generated by iconfont.cn
});

const menuItems = [
    {key: "menu1", name: "Dashboard", iconType: "default", icon: "dashboard", subMenus: [{key: "sub1-1", name: "Live Feed"}, {key: "sub1-2", name: "Past Data"}]},
    {key: "menu2", name: "Manage Employees", iconType: "custom", icon: "icon-imgreviewures2x1"},
    {key: "menu3", name: "Manage Organization", iconType: "custom", icon: "icon-organisation"},
    {key: "menu4", name: "Manage Shifts", iconType: "custom", icon: "icon-user-clock"},
    {key: "menu5", name: "Manage Leave", iconType: "default", icon: "carry-out"},
    {key: "menu6", name: "Manage Cameras", iconType: "default", icon: "video-camera"},
    {key: "menu7", name: "Support", iconType: "default", icon: "message"},
    {key: "menu8", name: "Settings", iconType: "default", icon: "setting"},
];

export default class SidebarComponent extends React.Component{

    state = {
        selectedKey: "menu1",
        openedMenu: ["menu1"],
        selectedSubMenu: ["sub1-1"]
    };

    handleMenuItemOnClick = (menu) => {
        this.setState({selectedKey: menu.key})
    };

    handleSubMenuOnClick = (menu) => {
        if (this.state.openedMenu.includes(menu.key)){
            this.setState({openedMenu: []})
        }
        else this.setState({openedMenu: [menu.key]})

    };

    handleSubMenuSelect = (menuKey) => {
        this.setState({selectedSubMenu: [menuKey]})
    };

    render() {
        return(
            <Sider width={250} style={{background: '#fff'}}>
                <Menu
                    mode="inline"
                    theme={"dark"}
                    defaultSelectedKeys={["sub1-1"]}
                    defaultOpenKeys={this.state.openedMenu}
                    style={{height: '100%', borderRight: 0, textAlign: "left", background: "#32363C"}}
                    onClick={this.handleMenuItemOnClick}
                >
                    {menuItems.map(menuItem => menuItem.subMenus ?
                        <SubMenu
                            key={menuItem.key}
                            title={
                                <span>
                                    {menuItem.iconType !== "custom" ?
                                        <Icon type={menuItem.icon}/>
                                        : <MyIcon type={menuItem.icon}/>
                                    }
                                    {menuItem.name}
                                </span>
                            }
                            style={this.state.openedMenu.includes("menu1") ? {background: "#212121"} : null}
                            onTitleClick={key => this.handleSubMenuOnClick(key)}
                        >
                            {menuItem.subMenus.map(subMenu => (
                                <Menu.Item
                                    key={subMenu.key}
                                    onClick={()=> this.handleSubMenuSelect(subMenu.key)}
                                    style={this.state.selectedSubMenu.includes(subMenu.key) ? {background: "#000c17", color: "#3A7AB0"} : null}
                                >
                                    {subMenu.key === "sub1-1" ? <Badge status="processing" /> : <Badge status="default" />}
                                    {subMenu.name}
                                </Menu.Item>))}
                        </SubMenu>
                        : <Menu.Item
                            key={menuItem.key}
                            style={this.state.selectedKey === menuItem.key ? {background: "#212121"} : null}
                        >
                            {menuItem.iconType !== "custom" ? <Icon type={menuItem.icon}/> : <MyIcon type={menuItem.icon}/>}
                            {menuItem.name}
                        </Menu.Item>
                    )}
                    <Menu.Item
                        key={"menu9"} style={this.state.selectedKey === "menu9" ?
                            {position:"absolute", left: 0, bottom: "40px", background: "#32363C"}
                        : {position:"absolute", left: 0, bottom: "40px", background: "#32363C"}}><a href={"tel:1800-3934-3490349"}> <Icon type="phone" /> 1800-3934-3490349 </a>
                    </Menu.Item>
                    <Menu.Item
                        key={"menu10"} style={this.state.selectedKey === "menu9" ?
                            {position:"absolute", left: 0, bottom: 0, background: "#32363C"}
                            : {position:"absolute", left: 0, bottom: 0, background: "#32363C"}}> <a href="mailto:helpdesk@ciphense.com"> <Icon type="mail" />helpdesk@ciphense.com </a>
                    </Menu.Item>
                </Menu>
            </Sider>
        )
    }
}